# Práctica de la librería Numpy

En este notebook, se desarrollarán una serie de tareas utilizando la librería Numpy (Numerical Python).

Se proponen y documentan posibles formas de resolver los ejercicios, pero las mismas no son únicas.

Siempre es una buena idea verificar la [Documentación Oficial de Numpy](https://numpy.org/devdocs/user/index.html), donde es posible encontrar todo tipo de información referida a esta librería. Y si te quedas trabado, busca en Google "como hacer [algo] con Numpy". Hay enormes probabilidades de que esa pregunta ya haya sido respondida!

In [ ]:
# Importamos Numpy con su abreviación "np"
import numpy as np


In [ ]:
# Podemos crear arrays de una dimensión con la función np.array()
array_unidim = np.array([1,2,3,4,5])

# O un array de dos dimensiones (bidimensional)
array_bidim = np.array([[1,2,3],
                       [4,5,6]])

# O un array de tres dimensiones (tridimensional)
array_tridim = np.array([[[1,2,3],
                        [4,5,6]],
                        [[7,8,9],
                         [10,11,12]]])


Para cada uno de estos arrays, podemos obtener sus propiedades, tales como su "forma", número de dimensiones, tipos de datos y tamaño.

In [ ]:
# Atributos del array unidimensional (forma, número de dimensiones, tipos de datos, tamaño, y tipo)
array_unidim.shape, array_unidim.ndim, array_unidim.dtype, array_unidim.size, type(array_unidim)


((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [ ]:
# Atributos del array bidimensional
array_bidim.shape, array_bidim.ndim, array_bidim.dtype, array_bidim.size, type(array_bidim)


((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [ ]:
# Atributos del array tridimensional
array_tridim.shape, array_tridim.ndim, array_tridim.dtype, array_tridim.size, type(array_tridim)


((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [ ]:
# Importamos pandas como pd, y creamos un DataFrame a partir del array bidimensional
import pandas as pd

datos = pd.DataFrame(array_bidim)
datos


In [10]:
# Creamos un array de tamaño 4x3, formado únicamente por unos (1)
unos = np.ones((4,3))
unos


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# Creamos un array de tamaño 2x4x3, formado únicamente por ceros (0)
cero = np.zeros((2,4,3))
cero


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
# Creamos un array de números en el rango de 0 a 100, con un paso de 5
array_1 = np.arange(0, 101, 5)
array_1


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [22]:
# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (2, 5)
array_2 = np.random.randint(0,10, (2, 5))
array_2


array([[1, 9, 1, 0, 4],
       [0, 5, 4, 0, 4]])

In [26]:
# Creamos un array de números aleatorios decimales comprendidos en entre 0 y 1, de tamaño (3, 5)
array_3 = np.random.random((3, 5))
array_3

array([[0.96027467, 0.44033445, 0.5596112 , 0.6559254 , 0.58415638],
       [0.3841932 , 0.03643052, 0.81492074, 0.06162712, 0.73773206],
       [0.38011404, 0.78026581, 0.4715666 , 0.02672274, 0.85398836]])

In [62]:
# Establecemos la "semilla" de números aleatorios en 27
np.random.seed(27)

# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (3, 5)
array_4 = np.random.randint(0, 10, (3, 5))
array_4


array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2],
       [1, 1, 4, 6, 3]])

¿Qué ocurre al correr la última celda nuevamente, a diferencia de las anteriores?

In [63]:
# Encontramos los valores únicos del array_4
np.unique(array_4)


array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [64]:
# Extraemos el elemento de índice 1 del array_4
array_4[1]


array([5, 8, 9, 1, 2])

In [65]:
# Extraemos las primeras dos filas del array_4
array_4[:2]


array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2]])

In [68]:
# Extraemos los dos primeros datos de las primeras dos filas del array_4
array_4[:2, :2]


array([[3, 8],
       [5, 8]])

In [72]:
# Creamos dos arrays de tamaño 3x4: uno relleno de números aleatorios entre 0 y 10, y otro relleno de unos
array_5 = np.random.randint(0, 10, (3, 4))
array_6 = np.ones((3, 4))


In [73]:
# invocamos el array_5
array_5


array([[1, 1, 7, 0],
       [7, 8, 4, 9],
       [0, 4, 7, 0]])

In [74]:
# invocamos el array_6
array_6


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [75]:
# Sumamos los dos arrays
array_5 + array_6


array([[ 2.,  2.,  8.,  1.],
       [ 8.,  9.,  5., 10.],
       [ 1.,  5.,  8.,  1.]])

In [77]:
# Creamos ahora un array de tamaño (4,3) lleno de unos
array_7 = np.ones((4, 3))
array_7


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [78]:
# Intentaremos sumar los arrays 6 y 7
array_6 + array_7


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

¿A qué se debe el error anterior? ¿Qué deberíamos tener en cuenta para que no suceda?

In [79]:
# Entonces crearemos otro array de tamaño (4,3) lleno de unos
array_8 = np.ones((4, 3))
array_8


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [80]:
# Restamos el array_8 al array_7
array_8 - array_7


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [85]:
# Creamos otros dos arrays de tamaño 3x3 con números aleatorios del 1 al 5
array_9 = np.random.randint(1, 5, (3, 3))
array_10 = np.random.randint(1, 5, (3, 3))


In [83]:
# invocamos el array_9
array_9


array([[2, 3, 3],
       [5, 4, 1],
       [4, 2, 2]])

In [86]:
# invocamos el array_10
array_10


array([[2, 3, 2],
       [1, 4, 4],
       [4, 1, 4]])

In [88]:
# Multiplicamos los últimos dos arrays entre sí
array_9 * array_10


array([[ 2,  6,  4],
       [ 2, 12, 16],
       [12,  3, 12]])

In [89]:
# Elevamos el array_9 al cuadrado
array_9 ** 2


array([[ 1,  4,  4],
       [ 4,  9, 16],
       [ 9,  9,  9]])

In [90]:
# Buscamos la raíz cuadrada del array_10
np.sqrt(array_10)


array([[1.41421356, 1.73205081, 1.41421356],
       [1.        , 2.        , 2.        ],
       [2.        , 1.        , 2.        ]])

In [91]:
# Hallamos el promedio de los valores del array_9
array_9.mean()


np.float64(2.5555555555555554)

In [92]:
# Hallamos el valor máximo de los valores del array_9
array_9.max()


np.int64(4)

In [93]:
# Hallamos el valor mínimo de los valores del array_9
array_9.min()


np.int64(1)

In [94]:
# Cambiamos la forma del array_9 por una de 9x1, y lo almacenamos como array_11
array_11 = array_9.reshape(9, 1)


In [99]:
# invocamos el array_11
array_11


array([[1],
       [2],
       [2],
       [2],
       [3],
       [4],
       [3],
       [3],
       [3]])

In [100]:
# Transponemos el array_11
array_11.T


array([[1, 2, 2, 2, 3, 4, 3, 3, 3]])

In [101]:
# Comparamos el array_9 y el array_10, para saber cuáles elementos del array_9 son mayores a los del array_10
array_12 = array_9 > array_10
array_12


array([[False, False, False],
       [ True, False, False],
       [False,  True, False]])

¿Qué tipos de datos forman parte del array de resultados?

In [102]:
# Veamos sus nuevos tipos de datos
array_12.dtype


dtype('bool')

In [103]:
# Alguno de los elementos del array_9 es igual su equivalente del array_10?
array_9 == array_10


array([[False, False,  True],
       [False, False,  True],
       [False, False, False]])

In [104]:
# Comparamos nuevamente ambos arrays, en esta ocasión con >=
array_9 >= array_10


array([[False, False,  True],
       [ True, False,  True],
       [False,  True, False]])

In [105]:
# Buscamos los elementos del array_9 que son mayores a 2
array_9 > 2


array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [106]:
# Ordenamos de menor a mayor los elementos dentro del array_9
np.sort(array_9)


array([[1, 2, 2],
       [2, 3, 4],
       [3, 3, 3]])